name: Cypress Tests

on: 
  push:
    branches: [main, testes]
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: 
        browser: [chrome] # começa só com chrome

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências 
        run: |
          npm install
          cd server && npm install
          cd ../web && npm install
      
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Limpar reports antigos
      run : |
        rm -rf cypress/reports

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v7
      with:
        start: |
          npm run start:back
          npm run start:front
        wait-on: 'http://localhost:3000,http://localhost:8080'
        wait-on-timeout: 120
        browser: ${{ matrix.browser }}
        spec: cypress/e2e/**.cy.js

  relatorio:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Gerar relatório Mochawesome
      if: always()
      run: |
        npm run report

    - name: Upload relatório
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-report
        path: ./cypress/reports

    - name: Upload evidências
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-artifacts
        path: |
          cypress/screenshots
          cypress/videos

    - name: Compactar relatório
      if: always()
      run: |
        zip -r report.zip cypress/reports

    - name: Enviar relatório por email
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Cypress Tests - ${{ job.status }}"
        to: ${{ secrets.EMAIL_TO }}
        from: "Cypress CI <${{ secrets.EMAIL_USERNAME }}>"
        body: |
          🚀 Execução dos testes finalizada

          📊 Status: ${{ job.status }}

          🔗 Ver pipeline:
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}